# .github/workflows/ci.yml

# Name for the workflow
name: "Node.js CI Workflow (From Scratch Example)"

# Triggers: Run on push/pull_request to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs to run
jobs:
  # Job identifier
  build-lint-test:
    # Runner environment
    runs-on: ubuntu-latest

    # Steps for the job
    steps:
      # 1. Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Use Node.js v20
          cache: 'npm'         # Enable npm dependency caching

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run Linter
      - name: Run linter
        run: npm run lint

      # 5. Run Tests
      - name: Run tests
        run: npm test

      # 6. Run Build step (if applicable)
      - name: Run build step
        run: npm run build

